export const lightsabers = [
    {
      id: "darkSaber",
      name: "Dark Saber",
      price: 497.65,
      src: "http://localhost:3000/assets/lightsabers/darksaber.webp",
      altText: "Dark Saber",
      initialQuantity: 1,
    },
    {
      id: "lukeSaber",
      name: "Luke Saber",
      price: 497.65,
      src:"http://localhost:3000/assets/lightsabers/lukelightsaber.webp",
      altText: "Luke Saber",
      initialQuantity: 1,
    },
    {
      id: "booneSaber",
      name: "Boone Saber",
      price: 497.65,
      src:"http://localhost:3000/assets/lightsabers/boonelightsaber.webp",
      altText: "Boone Saber",
      initialQuantity: 1,
    },
    {
      id: "vaderSaber",
      name: "Vader Saber",
      price: 497.65,
      src:"http://localhost:3000/assets/lightsabers/vaderlightsaber.webp",
      altText: "Vader Saber",
      initialQuantity: 1,
    },
    {
      id: "anakinsaber",
      name: "Anakin EP3 Saber",
      price: 497.65,
      src:"http://localhost:3000/assets/lightsabers/anakinlightsaber.jpg",
      altText: "Anakin Saber",
      initialQuantity: 1,
    },
    {
      id: "obiwonsaber",
      name: "Obi-Won EP3 Saber",
      price: 497.65,
      src:"http://localhost:3000/assets/lightsabers/obiwonlightsaber.jpg",
      altText: "Obi-Won Saber",
      initialQuantity: 1,
    },
  ];
  