export const lightsabers = [
  {
    id: "darkSaber",
    name: "Dark Saber",
    price: 497.65,
    src: "http://localhost:3000/assets/lightsabers/darksaber.webp",
    altText: "Dark Saber",
    initialQuantity: 1,
    reviews: Math.floor(Math.random() * (57 - 20 + 1)) + 20, // Random number between 20 and 57
    blade: "Proffie or SN-Pixel",
    shipping: "Free Shipping!"
  },
  {
    id: "lukeSaber",
    name: "Luke Saber",
    price: 497.65,
    src: "http://localhost:3000/assets/lightsabers/lukelightsaber.webp",
    altText: "Luke Saber",
    initialQuantity: 1,
    reviews: Math.floor(Math.random() * (57 - 20 + 1)) + 20,
    blade: "Proffie or SN-Pixel",
    shipping: "Free Shipping!"
  },
  {
    id: "booneSaber",
    name: "Boone Saber",
    price: 497.65,
    src: "http://localhost:3000/assets/lightsabers/boonelightsaber.webp",
    altText: "Boone Saber",
    initialQuantity: 1,
    reviews: Math.floor(Math.random() * (57 - 20 + 1)) + 20,
    blade: "Proffie or SN-Pixel",
    shipping: "Free Shipping!",
  },
  {
    id: "vaderSaber",
    name: "Vader Saber",
    price: 497.65,
    src: "http://localhost:3000/assets/lightsabers/vaderlightsaber.webp",
    altText: "Vader Saber",
    initialQuantity: 1,
    reviews: Math.floor(Math.random() * (57 - 20 + 1)) + 20,
    blade: "Proffie or SN-Pixel",
    shipping: "Free Shipping!",
  },
  {
    id: "anakinsaber",
    name: "Anakin EP3 Saber",
    price: 497.65,
    src: "http://localhost:3000/assets/lightsabers/anakinlightsaber.jpg",
    altText: "Anakin Saber",
    initialQuantity: 1,
    reviews: Math.floor(Math.random() * (57 - 20 + 1)) + 20,
    blade: "Proffie or SN-Pixel",
    shipping: "Free Shipping!",
  },
  {
    id: "obiwonsaber",
    name: "Obi-Won EP3 Saber",
    price: 497.65,
    src: "http://localhost:3000/assets/lightsabers/obiwonlightsaber.jpg",
    altText: "Obi-Won Saber",
    initialQuantity: 1,
    reviews: Math.floor(Math.random() * (57 - 20 + 1)) + 20,
    blade: "Proffie or SN-Pixel",
    shipping: "Free Shipping!",
  },
];
